#!/bin/csh

git remote add dbwy https://github.com/wavefunction91/chronusq.git
git remote add ligroup https://github.com/liresearchgroup/chronusq.git
git remote add apetrone https://github.com/alessiopetrone/chronusq.git
git remote add ssilwal https://github.com/silwalsajan/chronusq.git
git remote add hbliu https://github.com/uwhbliu/chronusq.git
git remote add jjgoings https://github.com/jjgoings/chronusq.git

git fetch dbwy
git fetch ligroup
git fetch apetrone
#git fetch ssilwal
git fetch hbliu
git fetch jjgoings
