#!/bin/sh

git remote add dbwy https://github.com/wavefunction91/chronusq.git
git remote add ligroup https://github.com/liresearchgroup/chronusq.git
git remote add apetrone https://github.com/alessiopetrone/chronusq.git
git remote add ssilwal https://github.com/silwalsajan/chronusq.git
git remote add hbliu https://github.com/uwhbliu/chronusq.git
git remote add jjgoings https://github.com/jjgoings/chronusq.git
git remote add plestran https://github.com/plestran/chronusq.git
git remote add kindrich https://github.com/kindrich/chronusq.git

