#!/bin/sh

cd deps/src
echo "Unpacking Libint"
tar xf libint-2.1.0-beta2.tgz
cd libint-2.1.0-beta2
./configure --prefix=$PWD/../.. --with-cxx=$CXX CXXFLAGS='-fPIC -O2'
echo "Compiling Libint"
make install -s -j$1
echo "Libint Compiled!"
cd ../../..
