#!/bin/sh

cd deps/src
svn co http://www.tddft.org/svn/libxc/trunk/ libxc
cd libxc
autoreconf -i
./configure --prefix=$PWD/../.. CC=gcc CFLAGS='-w -O3' --enable-shared --disable-fortran
make -j$1 install
cd ../../..
