#!/usr/bin/perl 
#Patrick Lestrange

use strict;
use warnings;
use Tie::File;

our (@file);

#Makes new input files based on old serial_incore.inp file
for(my $i = 0; $i < scalar @ARGV; $i++){
	my @string = split /\./, $ARGV[$i];
	$file[$i] = $string[0];
	print "file = $file[$i]\n";
	system(`../../../../build_gcc_libint_openmp/chronusq.py $file[$i]`);
  }


